### ISSUE TITLE
Hacktoberfest 2023: Call for Contributors!

### ISSUE THREAD

**Issue by naisofly** [surrealdb/awesome-surreal#35]
# **🚀Join Hacktoberfest 2023 with SurrealDB! 🚀**
Are you ready to take your development skills to the next level and win some awesome swag? Hacktoberfest is here, and SurrealDB invites you to participate in an exciting challenge, with the most powerful features, of the newly launched [SurrealDB 1.0](https://surrealdb.com/products)!

## 🏁 **Objective:** 
Create starter apps in your favorite programming framework using [SurrealDB's powerful SDKs](https://surrealdb.com/docs/integration/sdks). Supported SDKs are:
- [Rust](https://surrealdb.com/docs/integration/sdks/rust)
- JavaScript - [Vanilla JS](https://surrealdb.com/docs/integration/sdks/javascript), [Node JS](https://surrealdb.com/docs/integration/sdks/nodejs)
- [Python](https://surrealdb.com/docs/integration/sdks/python)    
    
    
## 🎉 **How to Participate:**
    
1. Get started with the ultimate multi-model database - [SurrealDB](https://surrealdb.com/docs/introduction/start). 
Develop easier. Build faster. Scale quicker with [SDKs](https://surrealdb.com/docs/integration/sdks)
2.  Read the [rules](https://hacktoberfest.com/participation/) & register at [hacktoberfest.com/register](https://hacktoberfest.com/register/)!
3. Contribute Pull Requests against this issue for the [Starter Kits section](https://github.com/surrealdb/awesome-surreal#starter-kits) of this repo!
  Some of the ideas from the community are listed below. Feel free to comment on which starter kit you'd like to work on for [Hacktoberfest](https://hacktoberfest.com/). If you have another idea for a starter kit, not currently on the list, please comment below with your idea and we'll add it!
    - [x] [Tauri - with Next.js](https://github.com/surrealdb/awesome-surreal/pull/40) @reymom 
    - [x] Rocket - @davidzr 
    - [ ] Ember
    - [ ] Svelte - @gusbuncedev 
    - [x] Vue - @inkollusireeshaadharani 
    - [ ] NuxtJS
      - [x] Minimal Starter Kit / Plugin by @dvanmali
      - [ ] Real-time Task Management App with @tarunsinghofficial 
    - [ ] React
      - [ ] @audreymengue
      - [ ] with Typescript @Sahil-Choudhary-17 
      - [ ] with Node @roshan-jha-23
      - [x] [with Node](https://github.com/surrealdb/awesome-surreal/pull/42) @MSaiKiran9
      - [ ] with Node @yashashwini16
      - [ ] with Node @harshil-junakiya
      - [ ] with Node @SoNiC-HeRE 
    - [ ] Node - @Abhi-Kamat 
    - [ ] NextJS 
      - [ ] @adeyinkaezra123 
      - [ ] @hridaya423 
    - [ ] Deno - with Typescript - @adeyinkaezra123 
    - [x] [Solid](https://github.com/surrealdb/awesome-surreal/pull/39) - @metruzanca 
    - [ ] Remix - @Jonyango 
    - [x] [Koa with Node](https://github.com/surrealdb/awesome-surreal/pull/41) - @jerempy 
    - [ ] Astro - @xkrishguptaa 
    - [ ] Qwik - @matthewcm 
    - [ ] Vanilla JS - with TensorFlow.js - @ju3tin 
    - [ ] Angular 16 + nodejs 18.10 (javascript+express) - @Divine1 
    - [x] FastAPI - @richie-omondi, with Next.js @marcdhi 
    - [x] Flask - @syedzubeen 
    - [ ] Django - @Moksh-10 
    - [x] Streamlit - @LuciAkirami 
    - [ ] Tauri + Vue.js + FastAPI Desktop Assistant - @DeepanshuMishra49 
    - [x] SpringBoot  - @PDROJACK 
    - [ ] Go - @sbshah97 
    
## 🌐 **Operations:** 
We're here to support you throughout the challenge! Join our [**#hacktoberfest2023** ](https://discordapp.com/channels/902568124350599239/1156547643145724005) channel on Discord for guidance and collaboration. We also offer [weekly developer office hours](https://github.com/orgs/surrealdb/discussions/2118) to assist you with any questions you may have. Keep an eye out for our [live events](https://www.eventbrite.co.uk/o/surrealdb-61957093863) in your timezone!

## :heavy_check_mark:   **Success Criteria:** 
- Every participant that meets the [Hacktoberfest rules](https://hacktoberfest.com/participation/) and has pull/merge requests against this issue is eligible for the rewards mentioned 💯 
- Starter kits should provide a **minimum** setup, ensuring developers can seamlessly use the latest version of [SurrealDB](https://surrealdb.com/products) in your chosen framework👌While simplicity is key, we also encourage custom starter kits tailored to specific needs.
- Your repository should have:
  - Include a clear, step-by-step [README](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes) for setup.  Include a GIF or screenshot showcasing the app's final result for developer reference.
  - Instructions to use your starter kit as a basis for other use cases.
  - Provide straightforward [Contribution Guides](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#examples-of-contribution-guidelines) for others to contribute effectively.

    
## 🤝 **Partners:** 
We're thrilled to partner with @illacloud, who share our passion for innovation and creativity. Check out the SurrealDB announcement on their Hacktoberfest [Livestream](https://www.youtube.com/live/acySNWm6BcY?si=f0d08AZCz8z8evTQ)!
Thanks again to @kunal-kushwaha for featuring this challenge on the ["A Crash Course on SurrealDB" livestream](https://www.youtube.com/live/rMJGKtl3y8E?si=hEJyi51f-JyE0L9T)!

## 💝 **Rewards:** 
Not only will you gain valuable experience, but you'll also have a chance to win exciting swag from the [SurrealDB Store](https://surrealdb.store/)!

**Comment by reymom** [comment]
Hi here, I am working on a starter app using Tauri (Rust SDK) together with Next.js for the frontend.

**Comment by naisofly** [comment]
Thanks @reymom! Added your name near Tauri in the issue above. Can't wait to see what you build! :grin:

**Comment by dvanmali** [comment]
Currently creating a Nuxt JS Minimal Starter Kit / Plugin

**Comment by naisofly** [comment]
Good to hear @dvanmali! Added your name above & can't wait to see what you build :grin:

**Comment by naisofly** [comment]
@audreymengue @Sahil-Choudhary-17 amazing!
Added your names above. Do reach out on Discord if you need anything!

**Comment by Moksh-10** [comment]
Hi @naisofly , I would like to create a starter kit with django , also I would like to contribute if there is any work to do with docker .

**Comment by roshan-jha-23** [comment]
@naisofly  hi, i would like to create a starter app using node and react js

**Comment by tarunsinghofficial** [comment]
> # **🚀Join Hacktoberfest 2023 with SurrealDB! 🚀**
> Are you ready to take your development skills to the next level and win some awesome swag? Hacktoberfest is here, and SurrealDB invites you to participate in an exciting challenge, with the most powerful features, of the newly launched [SurrealDB 1.0](https://surrealdb.com/products)!
> 
> ## 🏁 **Objective:**
> Create starter apps in your favorite programming framework using [SurrealDB's powerful SDKs](https://surrealdb.com/docs/integration/sdks). Supported SDKs are:
> 
> * [Rust](https://surrealdb.com/docs/integration/sdks/rust)
> * JavaScript - [Vanilla JS](https://surrealdb.com/docs/integration/sdks/javascript), [Node JS](https://surrealdb.com/docs/integration/sdks/nodejs)
> * [Python](https://surrealdb.com/docs/integration/sdks/python)
> 
> ## 🎉 **How to Participate:**
> 1. Get started with the ultimate multi-model database - [SurrealDB](https://surrealdb.com/docs/introduction/start).
>    Develop easier. Build faster. Scale quicker with [SDKs](https://surrealdb.com/docs/integration/sdks)
> 2. Read the [rules](https://hacktoberfest.com/participation/) & register at [hacktoberfest.com/register](https://hacktoberfest.com/register/)!
> 3. Contribute Pull Requests against this issue for the [Starter Kits section](https://github.com/surrealdb/awesome-surreal#starter-kits) of this repo!
>    Some of the ideas from the community are listed below. Feel free to comment on which starter kit you'd like to work on for [Hacktoberfest](https://hacktoberfest.com/). If you have another idea for a starter kit, not currently on the list, please comment below with your idea and we'll add it!
> 
> * [ ]  Tauri - @reymom
> * [ ]  Rocket
> * [ ]  [Svelte](https://github.com/spinspire/surrealdb-sveltekit-starter) - @jkdoshi
> * [ ]  Vue
> * [ ]  Nuxt JS - Minimal Starter Kit / Plugin by @dvanmali
> * [ ]  React - @audreymengue, with Typescript @Sahil-Choudhary-17
> * [ ]  FastAPI
> * [ ]  Flask
> * [ ]  Django
> 
> ## 🌐 **Operations:**
> We're here to support you throughout the challenge! Join our [**#hacktoberfest2023** ](https://discordapp.com/channels/902568124350599239/1156547643145724005) channel on Discord for guidance and collaboration. We also offer [weekly developer office hours](https://github.com/orgs/surrealdb/discussions/2118) to assist you with any questions you may have. Keep an eye out for our [live events](https://www.eventbrite.co.uk/o/surrealdb-61957093863) in your timezone!
> 
> ## 🤝 **Partners:**
> We're thrilled to partner with @illacloud, who share our passion for innovation and creativity. Check out the SurrealDB announcement on their Hacktoberfest [Livestream](https://www.youtube.com/live/acySNWm6BcY?si=f0d08AZCz8z8evTQ)!
> 
> ## 💝 **Rewards:**
> Not only will you gain valuable experience, but you'll also have a chance to win exciting swag from the [SurrealDB Store](https://surrealdb.store/)!

Hi @naisofly 👋, I would like to work on a Real-time Task Management App using NuxtJS and SurrealDB. Thanks.

**Comment by richie-omondi** [comment]
Hi @naisofly. I would like to work on a starter app using FastAPI and SurrealDB. Thanks

**Comment by Abhi-Kamat** [comment]
Hi @naisofly. I would like to work on a starter app using javascript and node js. Thanks

**Comment by Divine1** [comment]
Hi @naisofly 

Could you add `Angular + nodejs` in Starter kit section? i would like to work on that.
Just to confirm, Once the starter kit is completed from my end, Should i create a repository in my github login and share you the repository link for review?

**Comment by DeepanshuMishra49** [comment]
hey @naisofly 
I am working on a desktop assistant using Tauri + Vue.js + FastAPI

**Comment by syedzubeen** [comment]
Hey @naisofly 
Can you assign me the one for flask ?

**Comment by pragyamishra56** [comment]
@naisofly Excited to join Hacktoberfest2023 for the first time! Ready to contribute and learn. Eager to be part of this community

**Comment by inkollusireeshaadharani** [comment]
Hey @naisofly I would like to work on a starter app with Vue.js and SurrealDB

**Comment by naisofly** [comment]
@Moksh-10, checkout our [Deployment Guide using Kubernetes & Docker](https://surrealdb.com/docs/deployment/kubernetes), and of course [SurrealDB on Dockerhub](https://hub.docker.com/r/surrealdb/surrealdb)!
@roshan-jha-23 @tarunsinghofficial @richie-omondi @Abhi-Kamat @Divine1 @DeepanshuMishra49 @syedzubeen @inkollusireeshaadharani added all your names above. Do reach out on [Discord](https://discord.com/channels/902568124350599239/1156547643145724005) to share your progress and hope to see you at the [Developer Office Hours](https://discord.gg/p9TdtqZPBw?event=1158718562874175568) this Friday! If there's anything you'd like to showcase, do let us know!

@pragyamishra56 Love the enthusiasm! Let us know what tech stack you're interested in and we can get started!

**Comment by pragyamishra56** [comment]
@naisofly  I'm a frontend and UI enthusiast,  Eager to contribute and collaborate, a beginner in open source, enthusiastic about contributing to collaborative projects.

**Comment by sivasaran-22** [comment]
Hi there, I like to work with any python frameworks Eager to do my first contribution for this project 🙂

**Comment by MSaiKiran9** [comment]
Hi @naisofly I would like to work on a app using react & node starter app using surrealdb

**Comment by naisofly** [comment]
@pragyamishra56 Awesome! If there are any specific frontend technologies you'd like to use for this challenge do let us know!

@sivasaran-22, as you can see in the issue above, we have FastAPI by @richie-omondi, Flask by @syedzubeen, Django by @Moksh-10, so feel free to collaborate on one of these or use another Python framework. Let us know!

@MSaiKiran9, we also have @roshan-jha-23 building with React & Node, so perhaps there's some opportunity to collaborate, learn, and build something amazing as these are very popular frameworks!

**Comment by pragyamishra56** [comment]
@naisofly  Fantastic! Ready to dive in with HTML, CSS, Tailwind, Bootstrap, and JavaScript for a robust solution. Let's craft a seamless and responsive UI together. Could you assign me an issue if it would be possible then? I'm eager to contribute.

**Comment by sivasaran-22** [comment]
> @pragyamishra56 Awesome! If there are any specific frontend technologies you'd like to use for this challenge do let us know!
> 
> @sivasaran-22, as you can see in the issue above, we have FastAPI by @richie-omondi, Flask by @syedzubeen, Django by @Moksh-10, so feel free to collaborate on one of these or use another Python framework. Let us know!
> 
> @MSaiKiran9, we also have @roshan-jha-23 building with React & Node, so perhaps there's some opportunity to collaborate, learn, and build something amazing as these are very popular frameworks!
> 

Thanks for your reply @naisofly

**Comment by metruzanca** [comment]
Hey @naisofly, I'm a huge fan of Solidjs/Solidstart. I'd love to throw together a demo app akin to the existing [SurrealDB + SvelteKit Starter](https://github.com/spinspire/surrealdb-sveltekit-starter) by Jitesh Doshi.

**Comment by gusbuncedev** [comment]
Hey @naisofly, I am a svelte(kit) dev and would love to put together a starter kit utilising sveltekit and surrealdb :)

**Comment by Jonyango** [comment]
Hey @naisofly. I am trying out the remix framework and would love to put together a starter kit utilizing Remix and Surrealdb.

**Comment by naisofly** [comment]
@Jonyango Looks exciting! 🚀  Waiting eagerly to see what you build! 🙌 😁 Keep an eye out for our next [Developer Office Hours](https://github.com/orgs/surrealdb/discussions/2118) this Friday which will be focused on the JavaScript SDKs with @kearfy & @Ekwuno ! 🎉

**Comment by naisofly** [comment]
@pragyamishra56, I've been having a chat with our Senior Frontend Engineer - @akankshadharkar - about your idea to craft a seamless and responsive UI. Can you drop us a quick message in the [#hacktoberfest](https://discordapp.com/channels/902568124350599239/1156547643145724005) channel on the [SurrealDB Discord Server](https://discord.gg/surrealdb) and we can find the right project for you?

**Comment by yashashwini16** [comment]
Hey @naisofly I would like to work on starter app using Reactjs and Node

**Comment by naisofly** [comment]
@jerempy, @yashashwini16 added your names above! BTW @yashashwini16 we also have @MSaiKiran9 & @roshan-jha-23 building with the same stack so feel free to collaborate and build something amazing! 🙌

**Comment by yashashwini16** [comment]
@naisofly Sure maam . Thank you so much !

**Comment by xkrishguptaa** [comment]
Hi, I'm a huge fan of astro, can I work on an astro starter?

**Comment by naisofly** [comment]
@xkrishguptaa Sure thing! I've added it above. Remember to follow the Success Criteria mentioned above to make it as easy as possible for us to review & approve ✌️

**Comment by PDROJACK** [comment]
Hey I would love to create a SpringBoot Starter Kit ?

**Comment by aravindputrevu** [comment]
@PDROJACK yes, you can work on it. Please follow the hacktoberfest rules and check the success criteria mentioned above!

**Comment by naisofly** [comment]
@PDROJACK Added it above. Hope you checked out the [Java SDK](https://surrealdb.com/docs/integration/sdks/java) & please do reach out on the [#hacktoberfest](https://discord.com/channels/902568124350599239/1156547643145724005) channel if you have any questions!

**Comment by harshil-junakiya** [comment]
Hey @naisofly ,
I would like to work on a starter app in react & node using surrealdb

**Comment by adeyinkaezra123** [comment]
Hello, @naisofly, I'd like to make two starter app kit submissions across two major stacks,
1.  Nextjs and Nodejs
2. Deno.js and Typescript.

Thanks!

**Comment by hridaya423** [comment]
@naisofly  can i make a starter app kit submission with next.js

**Comment by hridaya423** [comment]
> Hello, @naisofly, I'd like to make two starter app kit submissions across two major stacks,
> 
> 1. Nextjs and Nodejs
> 2. Deno.js and Typescript.
> 
> Thanks!

Can i work with you on the next and node one?

**Comment by LuciAkirami** [comment]
Hello @naisofly , I would like to make a started kit with Python's Streamlit UI Framework and SurrealDB

**Comment by SoNiC-HeRE** [comment]
Hi @naisofly , I would like to make a starter kit with Node and React (Js)

**Comment by naisofly** [comment]
@harshil-junakiya @SoNiC-HeRE done! I suggest you check out the other React & Node PR in this repo so you're not reinventing the wheel here :)) You can also collab with @roshan-jha-23, @MSaiKiran9, @yashashwini16 who chose the same tech stack!

@adeyinkaezra123 @LuciAkirami added your names above ✅ Can't wait to see what you build! 😁

**Comment by matthewcm** [comment]
I would like to build a QWIK starter template: https://qwik.builder.io/

Resume-able front end framework.

**Comment by ju3tin** [comment]
I'm working on a tik-tok dance trainer using TensorFlow-js and vanilla JavaScript and SurrealDB to save the tensorflow outputs

**Comment by naisofly** [comment]
Exciting apps @matthewcm @ju3tin! Can't wait to see your apps & kindly ensure they follow the success criteria mentioned above   🙌

**Comment by sbshah97** [comment]
Hi, I'm looking to add a starter project for Go. Had a conversation with @phughk last night. Will create a PR in the next 24 hours as the starter project is almost ready.

**Comment by marcdhi** [comment]
Hey @naisofly  I would like to work on a starter app with FastAPI, NextJS & SurrealDB!

**Comment by richie-omondi** [comment]
> Hey @naisofly I would like to work on a starter app with FastAPI, NextJS & SurrealDB!

Can we work together on this? I'm already working on a starter kit with FastAPI but I wouldn't mind integrating it with NextJS.

**Comment by marcdhi** [comment]
> > Hey @naisofly I would like to work on a starter app with FastAPI, NextJS & SurrealDB!
> 
> Hey @marcdhi. Can we work together on this? I'm already working on a starter kit with FastAPI but I wouldn't mind integrating it with NextJS.

Yeah Sure! @richie-omondi !
