### ISSUE TITLE
Link to death URL in Tutorial

### ISSUE THREAD

**Issue by vle003** [surrealdb/awesome-surreal#85]
Link to Official and Community tutorials is not working: 

https://tutorials.surrealdb.com/

**Comment by tobiemh** [comment]
Hi @vle003 thanks for submitting this issue. The tutorials.surrealdb.com domain has been shutdown as it was out of date, and all links should either point to this repository (https://github.com/surrealdb/awesome-surreal) or to the examples repository (https://github.com/surrealdb/examples).

The link shouldn't be present any more, but can I ask if you found this link still visible somewhere?
